<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-11T07:15:50 BST" name="Default suite" finished-at="2020-06-11T07:17:02 BST" duration-ms="72467">
    <groups>
    </groups>
    <test started-at="2020-06-11T07:15:50 BST" name="Default test" finished-at="2020-06-11T07:17:02 BST" duration-ms="72467">
      <class name="workingwithtestng.Loing">
        <test-method signature="testcase1()[pri:0, instance:workingwithtestng.Loing@7995092a]" started-at="2020-06-11T07:15:50 BST" name="testcase1" finished-at="2020-06-11T07:16:09 BST" duration-ms="19548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method signature="testcase2()[pri:0, instance:workingwithtestng.Loing@7995092a]" started-at="2020-06-11T07:16:09 BST" name="testcase2" finished-at="2020-06-11T07:16:20 BST" duration-ms="10905" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [OrangeHRM - New Level of HR Management] but found [OrangeHRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OrangeHRM - New Level of HR Management] but found [OrangeHRM]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at workingwithtestng.Loing.testcase2(Loing.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method signature="testcase3()[pri:0, instance:workingwithtestng.Loing@7995092a]" started-at="2020-06-11T07:16:20 BST" name="testcase3" finished-at="2020-06-11T07:16:35 BST" duration-ms="14803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
        <test-method signature="testcase4()[pri:0, instance:workingwithtestng.Loing@7995092a]" started-at="2020-06-11T07:16:35 BST" name="testcase4" finished-at="2020-06-11T07:16:50 BST" duration-ms="14966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method signature="testcase5()[pri:0, instance:workingwithtestng.Loing@7995092a]" started-at="2020-06-11T07:16:50 BST" name="testcase5" finished-at="2020-06-11T07:17:02 BST" duration-ms="12076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase5 -->
      </class> <!-- workingwithtestng.Loing -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
